### ISSUE TITLE
Compact messages out of place

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [CapnKitten/Material-Discord#133]
![image](https://user-images.githubusercontent.com/44755101/104864138-11fc9400-5930-11eb-8cc2-cbb9119a5f81.png)
![image](https://user-images.githubusercontent.com/44755101/104864152-1d4fbf80-5930-11eb-8271-06c17be1b56d.png)
I've got the message-addon theme running. 

Can you look into this please? 
Thank you!

**Comment by CapnKitten** [comment]
Could you tell me what your chat font scaling and zoom level are?

**Comment by My-Name-Is-Adam** [comment]
15 and 80 - I've changed it to different sizes but it's not made any difference to my knowledge. 
![image](https://user-images.githubusercontent.com/44755101/104870606-d6b69100-5940-11eb-802c-e14efef52b9b.png)

**Comment by My-Name-Is-Adam** [comment]
Just realized it is now displaying differently to when I first reported it so I'm not sure what changed. I think an extra space would be enough. 
![image](https://user-images.githubusercontent.com/44755101/104870985-cbb03080-5941-11eb-95f1-b8b0ff5735ad.png)

**Comment by CapnKitten** [comment]
So with the same appearance settings, I'm not able to get the same issue. I remember this being an issue with compact messages a while ago, but I fixed it shortly after I knew about it. Have you tried completely restarting your Discord client?

![g7H7Q4](https://user-images.githubusercontent.com/4013216/104871931-6b59c880-591a-11eb-81e3-071496820574.png)

**Comment by My-Name-Is-Adam** [comment]
![image](https://user-images.githubusercontent.com/44755101/104873614-d8845280-5948-11eb-9ee3-7a73489e7d4c.png)
I've cleared the Cache storage and Application cache and it still looks the same. I've also restarted it and it hasn't fixed it. 
I've also noticed an issue with the inbox above.

Is [this](https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/CapnKitten/BetterDiscord/master/Themes/Material-Discord/css/Material-Discord_addon-messages.theme.css) the theme that should be used in conjunction?

**Comment by CapnKitten** [comment]
I updated the add-on theme a couple days ago with a couple updates/fixes (v1.0.3). Are you having the same issue after restarting your Discord client after the update?

**Comment by CapnKitten** [comment]
This is fixed with Material Discord v3.0.0 and the add-on messages theme v1.0.4.

**Comment by My-Name-Is-Adam** [comment]
Hi, I've updated both and cleared all the cache but still face the issue.

**Comment by CapnKitten** [comment]
You may have to backup your themes, plugins, and custom css and uninstall BetterDiscord, then try reinstalling it. I rewrote v3.0.0 from scratch, so no existing code is messing with the padding/text indent.
