### ISSUE TITLE
Latest (theme?) update seems to have broken material you color theming

### ISSUE THREAD

**Issue by LuminarySage** [CapnKitten/Material-Discord#247]
I just restarted my discord not 10 minutes ago and my material discord theme has changed back to the default blue color from the green color I set

This is the quickcss snippet I've been using:
```css
:root {
    --accent-hue: 110;
    --accent-saturation: 90%;
    --accent-lightness: 60%;
    
    --accent-text-color: #fff;
}

.theme-dark {
    --saturation-modifier: 0.175;
    --lightness-modifier: 0.2;
    --text-lightness-modifier: 1.0;
}

.theme-light {
    --saturation-modifier: 0.175;
    --lightness-modifier: 2.02;
    --text-lightness-modifier: 1.0;
}
```

**System info:**
Windows 11 24H2
Discord stable 399648 (5301daf)
Vencord 8023b1b (Standalone)

**Comment by LuminarySage** [comment]
If I copy the accent color values to the theme section like below then weirdly the main pane isn't colored? It applies to dms, servers, etc. as well
```css
:root {
    --accent-hue: 110;
    --accent-saturation: 90%;
    --accent-lightness: 60%;
    
    --accent-text-color: #fff;
}

.theme-dark {
    --accent-hue: 110;
    --accent-saturation: 90%;
    --accent-lightness: 60%;

    --saturation-modifier: 0.175;
    --lightness-modifier: 0.2;
    --text-lightness-modifier: 1.0;
}

.theme-light {
    --accent-hue: 110;
    --accent-saturation: 90%;
    --accent-lightness: 60%;

    --saturation-modifier: 0.175;
    --lightness-modifier: 2.02;
    --text-lightness-modifier: 1.0;
}
```

![Image](https://github.com/user-attachments/assets/ba7f2e4f-ba42-4844-9671-f3d2d3795b1c)

**Comment by Soulshot96** [comment]
> Same issue. Seems to be related to a Discord update since the last theme update was yesterday and Material You was working without issues.
> 
> Surprisingly, the theme update broke the chat box as well.
> 
> ![Image](https://github.com/user-attachments/assets/0e172f40-0da0-47f6-a4cc-407949aa169f)

Yea...this specifically is how I found this issue/thread. Already missing my chatbox. This is awful,

**Comment by CapnKitten** [comment]
Are all of you using Vencord?

**Comment by Soulshot96** [comment]
I am, yea.

**Comment by LuminarySage** [comment]
Yes, standalone version

**Comment by CapnKitten** [comment]
Vencord was having issues, and got an update at some point today. 94b258a is the current version of Vencord, so lemme know if you're still having issues after getting that update.

**Comment by CapnKitten** [comment]
I pushed an update that should fix it. Restart your discord app to get it.

On an unrelated note, the accent color variables only need to be changed in `:root`, so you can remove the accent hue, saturation, and lightness variables from `.theme-dark` and `.theme-light`

**Comment by LuminarySage** [comment]
> I pushed an update that should fix it. Restart your Discord app to get it. The main textbox is supposed to have a slightly different color for the actual text box you type in. It's to be more inline with Material 3 Expressive, however it can be reverted by making `--main-textarea-inner-color` transparent for the respective default Discord theme you're using.
> 
> On an unrelated note, the accent color variables only need to be changed in `:root`, so you can remove the accent hue, saturation, and lightness variables from `.theme-dark` and `.theme-light`.

I've always had my accent color vars in :root so restarting didn't actually fix anything for me

**Comment by LuminarySage** [comment]
Also since I don't put accent color vars outside of root, I've never had the weird dual color issue other ppl in here seem to have either fwiw

![Image](https://github.com/user-attachments/assets/cd073f5a-092d-48c8-aa63-e090f4a52258)

**Comment by CapnKitten** [comment]
> Text box has been fixed - but Material You still isn’t being applied strangely. I can confirm the link to the theme addon works since Vencord reports it’s a valid link.
> 
> ![Image](https://github.com/user-attachments/assets/8005a441-e2b5-40f1-9b3c-2903ca511c02)
> 
> These are supposed to be gray for instance:
> 
> ![Image](https://github.com/user-attachments/assets/5aac5aa5-bc80-4b20-b22b-60d2e891f65c)

The discord custom themes has never worked with Material You since they both override existing colors. That add-on also hasn't been updated for the new ui so it should've never been fully working.

**Comment by CapnKitten** [comment]
> > I pushed an update that should fix it. Restart your Discord app to get it. The main textbox is supposed to have a slightly different color for the actual text box you type in. It's to be more inline with Material 3 Expressive, however it can be reverted by making `--main-textarea-inner-color` transparent for the respective default Discord theme you're using.
> > On an unrelated note, the accent color variables only need to be changed in `:root`, so you can remove the accent hue, saturation, and lightness variables from `.theme-dark` and `.theme-light`.
> 
> I've always had my accent color vars in :root so restarting didn't actually fix or change anything for me

I found the issue, and it lies with Vencord. Custom css is loaded before any themes, so if your custom css is to customize any themes, not just Material Discord, it'll get overwritten with the ones within the theme file.

![Image](https://github.com/user-attachments/assets/6be2a6b7-58e0-438d-92e5-22e3fbcdf1ec)

The highlighted line is the custom css. Since the same exact variable is already defined in the theme, it's as if your custom css never existed.

What I recommend doing for the time being, because custom css definitely loaded after the themes before all these Vencord issues, is using a local theme and customizing it within the theme file.

**Comment by LuminarySage** [comment]
Editing the theme locally worked, thanks! Would it be ok to keep this issue open until vencord fixes theirs?

**Comment by CapnKitten** [comment]
That's fine.
